language: bash

addons:
  apt:
    update: true

services:
  - docker

install:
  - export DOCKERFILE_PATH=Dockerfile
  - export IMAGE_NAME=svn-server
  - source hooks/build
  - docker run --detach --publish 3690:3690 $IMAGE_NAME

script:
  - netstat -ln | grep 3690
